### ISSUE TITLE
need support to help operator-authors to move from full FBC to basic veneer

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-registry#1028]
in order to facilitate veneer adoption, it would be of great benefit to operator-authors to be able to convert a FBC to a basic veneer.  
semver represents add'l challenges due to highly-opinionated characteristics of bundle progress and channel naming.

**Comment by grokspawn** [comment]
With a bit of limited yq magic, you can turn an FBC(here: /tmp/t.yaml) into a basic veneer by doing (yq v4):
```bash
yq eval -i  'del select(.schema == "olm.bundle").properties' /tmp/t.yaml
yq eval -i  'del select(.schema == "olm.bundle").relatedImages' /tmp/t.yaml 
yq eval -i  'del select(.schema == "olm.bundle").package' /tmp/t.yaml 
yq eval -i  'del select(.schema == "olm.bundle").name' /tmp/t.yaml 
```

**Comment by joelanford** [comment]
A jq variant: 
```
opm render <catalogRef> -o json | jq 'if (.schema == "olm.bundle") then {schema: .schema, image: .image} else . end'
```

There might be a `yq` one liner equivalent rather than @grokspawn's 4 commands (not sure), but either way this should work.

There is at least one caveat: The `basic` veneer will render the full contents of every bundle, including all the `olm.bundle.object` properites (which means CRDs, CSVs, icons embedded in CSVs), so the `basic` veneer output will likely be an order of magnitude larger than an `opm migrate`-d catalog.

**Comment by everettraven** [comment]
The following should be an equivalent `yq` one liner:
```
yq eval -i 'select(.schema == "olm.bundle") = {"schema": .schema, "image": .image}' test.yaml
```
I tested this out and compared it to the 4 `yq` commands @grokspawn shared and from what I could tell the output was equivalent
