### ISSUE TITLE
Document how to start the registry locally, ...

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-registry#177]
## Questions

- Is it possible to document how to start the registry locally as it is mentioned with the README.md file ?
```
Using the catalog locally
grpcurl is a useful tool for interacting with the example catalog server.

$ grpcurl -plaintext  localhost:50051 list api.Registry
```
- Is it possible to include a `How To` step within the README.md file ? 
- Is the MANIFEST format used to create an image of a catalog already supported by OLM ? Since which version ?

**Comment by flickerfly** [comment]
Here's my quick start at documenting this: 

Once you've built the catalog container, it is simply a `docker run --rm -p 50051:50051 container-name` command. Then you should have port 50051 exposed on localhost.

I find it easiest to have grpcurl in another container and then use that docker container to connect to it. This gives you the option of being able to run `docker ps` to find the container name and then `docker info $name` to find the IP or name and use that instead of localhost if something in your config with docker networking blocks your access to the port directly.

GRPCurl in a container from the author:
`docker pull fullstorydev/grpcurl`

**Comment by flickerfly** [comment]
I'd like to suggest that this automation isn't appropriate on this issue.
