### ISSUE TITLE
Question About the operator bundle design

### ISSUE THREAD

**Issue by just1900** [operator-framework/operator-registry#181]
This is the operator bundle manifest tree now
```
 etcd
 ├── manifests
 │   ├── etcdcluster.crd.yaml
 │   └── etcdoperator.clusterserviceversion.yaml
 └── metadata
     └── annotations.yaml
```
And before this version, we are using an package.yaml file to declare metadata. And the fs tree looks like below
```
olm-catalog
└── nzk-operator
    ├── 0.1.0
    │   ├── nzk-operator.v0.1.0.clusterserviceversion.yaml
    │   └── nzk_v1alpha1_nzkcluster_crd.yaml
    └── nzk-operator.package.yaml
```
My question is what's the difference between these two and what are the advantages using annotations.yaml if I'm using the OLM?

**Comment by ecordell** [comment]
The bundle format, with `metadata` and `manifests` is the layout for a single operator's manifests. These get included in the bundle image, and an index is built by aggregating bundle images together.

The old format, with a package manifest, represented the entire set of related operators for a package in one directory. Now, manifests for an operator live in a separate image so that the full unpacked contents of every operator don't need to be stored in the index image.
