### ISSUE TITLE
Vendor directory is checked into github

### ISSUE THREAD

**Issue by LouisPlisso** [operator-framework/operator-registry#202]
Hi, I'm currently working on removing the un-necessary pinned versions from go.mod (see https://github.com/operator-framework/operator-registry/issues/201)

I have the code working on my local branch but because the vendor directory is checked-in, the size of my PR would be 3k lines.

I believe the best practices recommend to have the vendor directory outside of the repo as go.mod and go.sum provide the locked-in version without having to maintain the vendor directory in the repo

**Comment by kevinrizza** [comment]
@LouisPlisso 

I think this is a totally reasonable change, but unfortunately it's going to require more significant work than just removing this repo's vendor folder and getting the local build working. 

Today the operator-registry along with several other projects in the operator-framework are tied into and published as part of OpenShift. Today, that integration requires that the `vendor/` folder exists otherwise their automation (which runs in a restricted networking environment) will reject the build and fail. If we want to do this, we need to create a more clean split between the upstream repositories in the `operator-framework` on github and some kind of downstream mirroring/rebasing process that can include vendoring to satisfy that requirement.

There is an active effort around getting that upstream/downstream split started (sounds like in the next month or so? Not sure on the timeline exactly). Once that happens, the steps to getting a pr like that merged will be much simpler. In the meantime, if you want to just submit a PR that includes the vendor folder diff, I think that would be reasonable.

**Comment by LouisPlisso** [comment]
Thanks @kevinrizza 
I'll submit the PR including vendor for now then
