### ISSUE TITLE
Docs: Install/Setup of opm

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-registry#214]
I've not yet found documentation on the installation or setup of opm. If I'm just missing it, maybe add a link to the top [opm tooling](https://github.com/operator-framework/operator-registry/blob/master/docs/design/opm-tooling.md).

**Comment by flickerfly** [comment]
I'd like to suggest that this automation isn't appropriate on this issue.

**Comment by flickerfly** [comment]
I'd like to suggest that this automation isn't appropriate on this issue.

**Comment by ecordell** [comment]
Since this issue was filed, the release process has been improved, and binaries are now available with clear names in each release. For example: https://github.com/operator-framework/operator-registry/releases/tag/v1.15.3

(also I have disabled stalebot until we can resolve the conflict with the openshift bot)
