### ISSUE TITLE
opm:  add version command

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-registry#231]
`opm` needs a `version` command

Example:
```
$ opm version 
opm-1.16.1-builddetails
```
Right now, to detect the version, one must compare the byte image with that from the releases page to determine which version is used.

**Comment by nathanbrophy** [comment]
@ecordell I wanted to check in on this ticket.  Is this something being worked on by the maintainers or contributors for the project currently?  If not, I can attempt to implement this in a consistent way as the operator-sdk tooling.

If this issue is something you would like me (a first time contributor) to attempt, then I can provide a short write up on the idea to implement in the issue and get a consensus before implementation?

**Comment by cdjohnson** [comment]
Appears to have been added in release 1.12.3 using this PR: https://github.com/operator-framework/operator-registry/pull/321
