### ISSUE TITLE
Running opm alpha bundle build generates metadata directory in root of the project

### ISSUE THREAD

**Issue by gnufied** [operator-framework/operator-registry#275]
I have a project where all my registry related bundle files are in a `bundle` subdirectory:

```
╰─aws-ebs-csi-driver-operator/bundle> tree .
.
├── bundle.Dockerfile
├── manifests
│   ├── aws-csi-driver.crd.yaml
│   └── aws-ebs-csi-driver-operator.clusterserviceversion.yaml
└── metadata
    └── annotations.yaml
```

When I run command:

```
opm alpha bundle build --directory . --tag quay.io/gnufied/ebs-csi-driver-operator-manifest:0.0.1 --package aws-ebs-csi-driver-operator --channels preview --default preview
```

from `bundle` directory, it surprisingly creates a `metadata` directory in root of the project.

**Comment by kevinrizza** [comment]
@gnufied This is intentional. `opm alpha bundle generate` is intended to be a run once scaffolding command to build a bundle either from a raw set of manifests or in some specific cases intended to migrate bundles from the old registry nested directory structure to a directory for bundles. By default, it creates the `/metadata/` directory at the same directory level as your `/manifests/` directory (which you have defined in your command as the current working directory).

This is intentional because bundle generate is attempting to create the same directory structure on disk as the one expected to live in the bundle image.

**Comment by gnufied** [comment]
It is creating metadata directory one level below the current working directory. So I run the `opm alpha bundle build` command from `bundle` directory but then it creates a `metadata` directory in `bundle/..` directory (i.e one level below and root of the project)

**Comment by kevinrizza** [comment]
Right, it's not about where you are running the command, it is attempting to put the `metadata/` directory in the same parent directory as whatever you specify `--directory`, which is implied to be your version of the `manifests/` directory.

Try passing the `--output-dir` flag as well to see what the tool is attempting to reproduce. It's just different knobs on "making some directory have a metadata folder at the same level as the manifests folder, wherever that is"
