### ISSUE TITLE
registry-server does not pull updated version of an index image

### ISSUE THREAD

**Issue by LPowlett** [operator-framework/operator-registry#292]
If I push an updated revision of my index image containing a modified CSV (same name/tag, different digest), the catalogsource pods Image ID still points to the old images digest. Restarting the pod or re-creating the catalog source have no effect.

**Steps to reproduce**

1. Generate index image `my-registry/my-namespace/my-index:v1.0.0` using `opm index add`
2. Push image to registry `my-registry/my-namespace/my-index:v1.0.0` (`digest: sha256: abc`)
3. Create catalog source pointing at `my-registry/my-namespace/my-index:v1.0.0` 

```
$ oc describe pod my-catalog-pod | grep "Image ID" 
Image ID: my-registry/my-namespace/my-index:v1.0.0@sha256:abc
```
4. Change a field in my local copy of the CSV (e.g. `spec.description`)
5. Generate a new index image `my-registry/my-namespace/my-index:v1.0.0` using `opm index add`
6. Push new image `my-registry/my-namespace/my-index:v1.0.0` to registry (`digest: sha256: xyz`)
7. Restart `my-catalog-pod` or recreate the catalog source

```
$ oc describe pod my-catalog-pod | grep "Image ID" 
Image ID: my-registry/my-namespace/my-index:v1.0.0@sha256:abc
```

**Expected behaviour**

_After step 6/7_

```
$ oc describe pod my-catalog-pod | grep "Image ID" 
Image ID: my-registry/my-namespace/my-index:v1.0.0@sha256:xyz
```

**Comment by ecordell** [comment]
You may be interested in the the updateStrategy for CatalogSources: https://github.com/operator-framework/operator-lifecycle-manager/blob/11a7dbbb19da9144e3050b92fa269719c09869f1/doc/design/catalog-polling.md#example-spec

Alternatively, you can use digest references in the `image` field, and update it when the content changes.

**Comment by hassenius** [comment]
I have been using the update strategy with a reasonable polling interval, but also find that the image does not update, even after days.
I do notice that when I do `oc describe catalogsource my_catalogsource` the `spec` does not include any information about `updateStrategy` (although the `Annotations: kubectl.kubernetes.io/last-applied-configuration` does).

The problem with updating the digest reference in the image field for me, is that it turns it from being a pull mechanism rather than a push mechanism.

**Comment by ecordell** [comment]
Since openshift 4.6 was released, all openshift clusters use the polling update strategy. Whatever issue was being hit here, I don't think it exists anymore.

Also, if this is a concern in the future, the CatalogSource on the cluster can point to digests instead of tags. This is much easier to reason about when you are developing a catalog (and faster; no need to wait for a poll)
