### ISSUE TITLE
opm tool on macOS should default to docker builds

### ISSUE THREAD

**Issue by wkulhanek** [operator-framework/operator-registry#409]
There is no podman on macOS. Therefore it might be nice if the opm tool on macOS defaulted to `--build-tool docker`.

**Comment by wtrocki** [comment]
```
alias podman="docker"
```

**Comment by exdx** [comment]
I agree. Even though there is some version of podman for macOS (see https://podman.io/getting-started/installation#macos) it's not what most macOS users use, they would use docker instead. The steps to setup podman on macOS properly are non-trivial (https://www.redhat.com/sysadmin/replace-docker-podman-macos). 

Once we add the declaritive config APIs these types of imperative commands that rely on a container tool will become less relevant, since it will be up to the user to decide which tool to use and opm will not shell out to these tools directly.
