### ISSUE TITLE
OPM as an API

### ISSUE THREAD

**Issue by deekshahegde86** [operator-framework/operator-registry#634]
As of today we can use OPM as a CLI tool. Is there a go client package for opm.

**Comment by exdx** [comment]
If we export functions, they are public APIs, and you are free to use any of those exported functions. It should have the same guarantees as any other Go API with respect to semver, as the registry project is already at v1. Since we are at v1 we should not break anything until we move to the v2 major semver version. 

There can be follow-up work regarding the documentation to match our support statement for our APIs and make it easier for users to import opm-related code into their projects as a library.
