### ISSUE TITLE
Support  opm registry rm bundle by special version ？

### ISSUE THREAD

**Issue by aiyijing** [operator-framework/operator-registry#761]
I‘ve seen the implement of the ”opm registry rm“，but it can only remove pacakge
that have all bundle version.
There are tow struct of Bundle,one is api.Bundle,other one is registry.Bundle.
So, It seems very difficult that to finish it，Is there easy way to remove special
version bundle？

**Comment by kevinrizza** [comment]
We don't have a way of trivially implementing something like this because of the way that graph metadata is implicitly encoded into the individual operator bundles. We are attempting to move away from that encoding and are in the process of replacing it with a new file based catalog format that separates the graph metadata into the index image itself. When that is done, it should be a simple matter of modifying a json file representation of your index without the need for any sort of explicit imperative command like `opm registry rm`, which has already begun a deprecation process.
