### ISSUE TITLE
Unable to run e2e tests locally: unauthorized

### ISSUE THREAD

**Issue by josefkarasek** [operator-framework/operator-registry#764]
Running `make e2e` results in:
```
STEP: pushing bundle
The push refers to repository [quay.io/olmtest/e2e-bundle]
7130ee73157e: Preparing
a701425d27d4: Preparing
unauthorized: access to the requested resource is not authorized
```

The image name `olmtest/e2e-bundle` is hard-coded in the testsuite.
Having the ability to a) not push the image to a remote registry or b) customize the image name would make adding new tests easier.

**Comment by kevinrizza** [comment]
I think at one point we had a `make-e2e-local` make target. At one point we had e2e jobs that knew how to start an ephemeral container registry that could be used just in the scope of these tests and then was torn down (rather than relying on a public registry over the wire). In order to get this working again, we should probably resurrect that effort.
