### ISSUE TITLE
opm: Dont pull index images if its present locally?

### ISSUE THREAD

**Issue by ashishmax31** [operator-framework/operator-registry#885]
We've been using the `indexer` package at `https://github.com/operator-framework/operator-registry/blob/master/pkg/lib/indexer/indexer.go` in some of our code to extract bundle information from an index image. We've noticed that the package always assumes that the index image is present in a remote registry and tries to pull it[1]. Why can't we have a simple check to determine if the image is present locally before trying to pull it?

I'll be happy to create a fix for this if thats okay, what do you guys think?
 
[1] https://github.com/operator-framework/operator-registry/blob/master/pkg/lib/indexer/indexer.go#L350

/kind feature

**Comment by dinhxuanvu** [comment]
While I understand the reason for your request, I don't think OLM is in the position to support all local image formats that may be different between different toolings/runtimes. For index image, I would recommend you to use the new file-based catalog which essentially is a JSON/YAML blob that you modify as you wish before building an index image later on. In that way, you only need to work with a local file instead of an image. https://olm.operatorframework.io/docs/reference/file-based-catalogs/

**Comment by joelanford** [comment]
I think we can close this based on the comment I left in the PR ([here](https://github.com/operator-framework/operator-registry/pull/892#issuecomment-1006125296))

@ashishmax31 please feel free to open a new issue if you have any more questions or requests!
