### ISSUE TITLE
Is it possible to render the operatorhub.io website from a file-based catalog?

### ISSUE THREAD

**Issue by mvalarh** [operator-framework/operator-registry#886]
I started index image 
```
podman run -d -p 50051:50051 --name registry quay.io/operatorhubio/catalog_tmp:latest
```
and i am trying to get cvsjson out of `aiven-operator` package

`csvJson` is not shown for version `aiven-operator.v0.1.1` 
```
$  grpcurl -plaintext -d '{ "pkgName": "aiven-operator", "csvName" : "aiven-operator.v0.1.1", "channelName": "alpha" }' localhost:50051 api.Registry.GetBundle | jq .csvJson
null
```
But it is ok for `aiven-operator.v0.2.0`
```
$  grpcurl -plaintext -d '{ "pkgName": "aiven-operator", "csvName" : "aiven-operator.v0.2.0", "channelName": "alpha" }' localhost:50051 api.Registry.GetBundle | jq .csvJson
"{\"apiVersion\":\"operators.coreos.com/v1alpha1\",\"kind\":\"ClusterServiceVersion\",\"metadata\":{\"annotations\":{\"alm-examples\":\"[]\",\"capabilities\":\"Basic Install\",\"categories\":\"Cloud Provider\",\"containerImage\":\"aivenoy/aiven-operator:v0.2.0\",\"description\":\"Manage your https://aiven.io resources with Kubernetes.\",\"operators.operatorframework.io/builder\":\"operator-sdk-v1.14.0+git\",\"operators.operatorframework.io/project_layout\":\"go.kubebuilder.io/v2\",\"repository\":\"https://github.com/aiven/aiven-operator\"},\"name\":\"aiven-o
...
```

Can you give me hint what to do? Or is it a bug?

**Comment by joelanford** [comment]
This likely means that v0.1.1 is not a channel head. SQLite catalogs only ever store CSVs for channel heads, so migrating an SQLite db to FBC will result in just channel heads having csvJson returned in bundle results.

**Comment by mvalarh** [comment]
But if will will not use migrate, but we build normal FBC, will it return csvJson in all bundles?

**Comment by joelanford** [comment]
That's correct. There's no use for non head CSVs though. Leaving non-head CSVs in the catalog doesn't hurt anything other than bloating the size of the catalog.

**Comment by mvalarh** [comment]
Yes. But we need to fill information for web page https://operatorhub.io/ and probably for ocp web page also. So would it be possible to add it. If not by default, than can we have some switch to enable this while doing `opm render`

**Comment by joelanford** [comment]
Yes, it is _possible_ to build a file-based catalog image that contains the CSV for every single bundle. However, I'm not sure its advisable since none of the on-cluster components require or use non-head CSVs. Increasing the size of the on-cluster image would waste bandwidth and disk space on-cluster.

Let's discuss this use case further. Some alternatives include:
1. Using the channel-heads-only catalog image to derive the data necessary to render operatorhub.io by iterating the bundles and extracting the CSV from the referenced image.
2. At catalog build time, build the fully populated catalog, publish it under a new tag, then strip the `olm.bundle.manifest` properties from it and publish that one under the existing tag.

**Comment by mvalarh** [comment]
I think that 2nd option could work, if i understand it right. I would assume that there would be option in `opm render --all-csv` or something like this. And then we would use this option for k8s operators since it is needed for webpage and for ocp we would not include this option, so image would not be big

**Comment by cdjohnson** [comment]
@joelanford 

Use cases for preserving the entire channel as written. vs. just the heads:
1.  Use of `startingCSV` with manual subscriptions (to install older versions)
2. Use of dependencies.yaml with an package dependency with a fixed upper range that's not part of the head (pinning to older versions)
3. Presevation of non-skipped (not using `skips` or `olm.skipRange`) releases when using `replaces` to verify that existing installations can step through those releases.

It certainly seems like `migrate` should preserve exactly what you had in your catalog by default rather than making assumptions that heads-only (truncated) channels is appropriate.

**Comment by joelanford** [comment]
> It certainly seems like migrate should preserve exactly what you had in your catalog by default rather than making assumptions that heads-only (truncated) channels is appropriate.

Just to clarify, `migrate` does preserve the original catalog, including all of the channel entries. What it _doesn't_ do is add anything extra that is not present in the original catalog.

The original request was asking if `migrate` would result in every bundle including an `olm.bundle.object` containing that bundle's CSV. The answer to that is "the migrated output will contain whatever the original catalog contained", and based on how `opm` has built sqlite based catalogs in the past, that typically means that _only_ channel heads will have `olm.bundle.object` CSVs.
