### ISSUE TITLE
Bump repository to Go 1.17 and k8s 0.23.x

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-registry#918]
Update the repositories Go and k8s dependencies to the latest versions.

AC:
- Update the root go.mod and github actions to use Go 1.17 versions
- Update the root go.mod and bump the k8s-related dependencies to 1.23.x and fix any logr breaking changes that come with the latest release.

**Comment by Andrew-Lees11** [comment]
Is there any update on this issue? Our vulnerability scan are finding vulnerabilities in the OPM builder that would be fixed by upgrading the go version.

**Comment by Andrew-Lees11** [comment]
For anyone following this issue, The go version has been bumped to 1.17 and is being used in upstream-registry-builder v1.21.0 however I cannot see a release yet for upstream-opm-builder with this version. 
The registry builder fixes the go vulnerabilities for opm however vulnerabilities are still present in our scans due to using an old version of `grpc-health-probe`. I have raised a [pr](https://github.com/operator-framework/operator-registry/pull/940) for updating this.

**Comment by timflannagan** [comment]
It looks like we're on Go 1.18 and k8s 1.24.x so I'm going to close this out.
